---
dist: trusty

matrix:
  fast_finish: true

services:
  - docker

env:
  matrix: # each entry is its own run
    - IMAGE: centos7
    - IMAGE: xenial
    - IMAGE: loki
    - IMAGE: trusty

script: make test

notifications:
  email:
    on_success: never
    on_failure: never
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
