---
# magic cd to /vagrant on login
- name: insert magic cd
  blockinfile:
    path: "{{ shell_config_file }}"
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    mode: "0750"
    block: "{{ shell_magic_template }}"
  become: true
  become_user: "{{ vagrant_user }}"
  when: shell_config_file is defined and shell_magic_template is defined

# when unable to find a shell configuration file or a shell template, fail
- name: fail when shell config file or shell template is undefined
  fail: msg="Shell configuration file and/or shell magic template are undefined."
  when: shell_config_file is undefined or shell_magic_template is undefined
