---
- name: include os facts
  include: discover/os.yml

# load variables per os and release
- name: load variables
  include_vars: "{{ vars_list }}"
  with_items:
    - "{{ os_name }}/common.yml"
    - "{{ os_name }}/{{ os_release }}.yml"
  loop_control: { loop_var: vars_list }

# install utility packages
- name: utility packages
  include: utility-packages.yml

# configure shell
- name: configure shell
  include: shell.yml
