---
# load variables per distro/version
- name: load per-distribution variables
  include_vars: "{{ per_distro_vars }}"
  with_items:
    - "distro/{{ ansible_distribution | lower }}/common.yml"
    - "distro/{{ ansible_distribution | lower }}/{{ ansible_distribution | lower }}{{ ansible_distribution_version.split('.') | first | lower }}.yml"
  loop_control: { loop_var: per_distro_vars }

# include per-distro tweaks
- name: include per-distribution tasks
  include: "{{ per_distro_tasks }}"
  with_items:
    - "distro/{{ ansible_distribution | lower }}/common.yml"
    - "distro/{{ ansible_distribution | lower }}/{{ ansible_distribution | lower }}{{ ansible_distribution_version.split('.') | first | lower }}.yml"
  loop_control: { loop_var: per_distro_tasks }

# install distro packages
- name: install distribution specific packages
  package: name={{ item }} state=present
  with_items: "{{ distro_packages }}"
  when: distro_packages is defined and len(distro_packages) > 0

# install utility packages
- name: utility packages
  include: utility-packages.yml

# configure shell
- name: configure shell
  include: shell.yml

# configure selinux
- name: configure selinux
  include: selinux.yml
  # when on an selinux system and the currently-running kernel has selinux loaded as the mac system (as opposed to
  # AppArmor, SMACK, etc.)
  when: ansible_selinux is defined
