---
- name: include ubuntu variables
  include_vars: ubuntu/common.yml
  when: is_ubuntu_derivative

- name: include trusty variables
  include_vars: ubuntu/trusty.yml
  when: is_ubuntu_trusty_derivative

- name: include xenial variables
  include_vars: ubuntu/xenial.yml
  when: is_ubuntu_xenial_derivative

- name: include redhat variables
  include_vars: "{{ vars_list }}"
  with_items:
    - redhat/common.yml
    - redhat/rhel7.yml
  loop_control: { loop_var: vars_list }
  when: is_redhat_derivative

# create magic cd to /vagrant on login
- name: insert magic cd
  template:
    src: vagrant-magic.sh.j2
    dest: /etc/profile.d/vagrant-magic.sh
    owner: root
    group: root
    mode: "0644"
  become: true

# update cache on ubuntu
- name: update cache
  apt: update_cache=yes cache_valid_time=2700
  when: is_ubuntu_derivative
  become: true

# install epel on redhat
- name: install epel
  package: name=epel-release state=present
  when: is_redhat_derivative
  become: true

# install utility packages
- name: install utility packages
  package: name={{ item }} state=present
  with_items: "{{ vagrant_utility_packages }}"
  become: true
