---
- name: red herring test
  shell: test -f /etc/selinux/config
  failed_when: false
  changed_when: false
  register: red_herring

- name: establish red herring
  set_fact:
    is_red_herring: "{{ red_herring.rc != 0 }}"

- name: setenforce 1
  selinux: state=enforcing # roll deep
  when: ansible_selinux is defined and not is_red_herring
