---
- name: update cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_distribution|lower == "ubuntu"

- name: install epel
  yum:
    name: epel-release
    state: present
  when: ansible_distribution|lower == "redhat"

# install utility packages
- name: install utility packages
  package: name={{ item }} state=present
  with_items: "{{ vagrant_utility_packages }}"
